version: "3"
services:
  db:
    container_name: db
    image: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"

  # db_app:
  #   container_name: db_app
  #   image: postgres
  #   volumes:
  #     - ./db_data_app:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: app_db
  #   ports:
  #     - "5434:5432"

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"

  server:
    build: ../end-end-authservice
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth_db
      DB_PORT: 5432
      NODE_ENV: docker
      SECRET: secret

  # server_app:
  #   build: ../ToDos_app
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     DB_HOST: db_app
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_NAME: app_db
  #     DB_PORT: 5432
  #     NODE_ENV: docker

  migration:
    build:
      context: ../end-end-authservice
      dockerfile: Dockerfile.migration
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: auth_db
      DB_PORT: 5432
      NODE_ENV: migration

  # migration_app:
  #   build:
  #     context: ../ToDos_app
  #     dockerfile: Dockerfile.migration
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   environment:
  #     DB_HOST: db_app
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_NAME: app_db
  #     DB_PORT: 5432
  #     NODE_ENV: migration
